on:
  pull_request:
    paths:
      - 'helmfile.d/*.gotmpl'
      - 'helmfile.d/*.yaml'
jobs:
  update:
    if: startsWith(github.head_ref, 'renovate/*')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Get changed files
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "changed=$CHANGED_FILES" >> $GITHUB_OUTPUT
      - name: Print changed files
        run: |
          echo "Changed files: ${{ steps.changes.outputs.changed }}"
