---
# Source: external-dns/templates/secret.yaml
# Source: external-dns/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: "external-dns"
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.15.1
    helm.sh/chart: external-dns-8.7.1
type: Opaque
data:
  azure.json: "ewogICJ0ZW5hbnRJZCI6ICJhYWFhYWFhYS1iYmJiYmJiLWNjY2NjY2MtZGRkZGRkLWZmZmZmZmYiLAogICJzdWJzY3JpcHRpb25JZCI6ICJub25lIiwKICAicmVzb3VyY2VHcm91cCI6ICJyZy1kbnMiLAogICJ1c2VXb3JrbG9hZElkZW50aXR5RXh0ZW5zaW9uIjogIHRydWUsCn0K"
