---
# Source: loki/templates/index-gateway/poddisruptionbudget-index-gateway.yaml
# Source: loki/templates/index-gateway/poddisruptionbudget-index-gateway.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-index-gateway
  namespace: observability
  labels:
    helm.sh/chart: loki-6.24.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "3.3.2"
    app.kubernetes.io/component: index-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: index-gateway
  maxUnavailable: 1
