---
# Source: opentelemetry-operator/templates/serviceaccount.yaml
# Source: opentelemetry-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-operator
  namespace: observability
  labels:
    helm.sh/chart: opentelemetry-operator-0.78.1
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/version: "0.116.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: opentelemetry-operator
    app.kubernetes.io/component: controller-manager
