---
# Source: loki/templates/ingester/poddisruptionbudget-ingester.yaml
# Source: loki/templates/ingester/poddisruptionbudget-ingester.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-ingester
  namespace: observability
  labels:
    helm.sh/chart: loki-6.24.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "3.3.2"
    app.kubernetes.io/component: ingester
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: ingester
    matchExpressions:
      - key: rollout-group
        operator: NotIn
        values:
          - 'ingester'
  maxUnavailable: 1
